<?php

namespace redemaroc\redeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * avisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class avisRepository extends EntityRepository
{
}
