<?php

namespace redemaroc\redeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * avisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class avisRepository extends EntityRepository
{

    public function getComment($produit_id)
    {
        /*$qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.avis = :produit_id')
            ->addOrderBy('c.created')
            ->setParameter('produit_id', $produit_id);

       /* if (false === is_null($approved))
            $qb->andWhere('c.approved = :approved')
                ->setParameter('approved', $approved);*/

        /*return $qb->getQuery()
            ->getResult();*/


    }

}
