<?php

namespace redemaroc\redeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * referRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class referRepository extends EntityRepository
{
}
